### ISSUE TITLE
Using colors to map normalized and original text

### ISSUE THREAD

**Issue by shaolintl** [normativeai/frontend#13]
On the original text tab, a user should be able to apply a color to one or more sentences.
The same color can be applied to the normalized text in the normalization tab.
The vocabulary should not contain colors.
This will give us another dimension of mapping the two texts.

**Comment by lex-lex** [comment]
I'm not sure I completely understand the proposal. Can you elaborate?

**Comment by shaolintl** [comment]
Yes, the attached file shows an example using the three possible tabs. Please tell me if more elaboration is needed.

![nai_colors](https://user-images.githubusercontent.com/5831765/53589691-4c1fe980-3b90-11e9-9f31-5abf2652235f.png)

**Comment by lex-lex** [comment]
We are now mapping terms to colors, but not whole annotated text parts. This seems to be what we agreed on in the last meeting. So I guess this ticket is resolved. Reopen if I misunderstood.
