### ISSUE TITLE
Description texts

### ISSUE THREAD

**Issue by lex-lex** [normativeai/frontend#19]
When not logged in, the landing page still states some "lorem ipsum" text-alikes. Maybe we should think of something to write there for the demo?

**Comment by shaolintl** [comment]
I added some basic text. Improvements are welcomed!

**Comment by terezanovot** [comment]
I am writing some text for description page today, I will send it tomorrow.

**Comment by shaolintl** [comment]
@Tereza Novotná <tereza.novotn@gmail.com> Please have a look at what I
wrote already...

**Comment by terezanovot** [comment]
Of course, but I still see only yada yada...

**Comment by shaolintl** [comment]
ctrl+shift+r

**Comment by terezanovot** [comment]
Ok, i see now, thank you!
