### ISSUE TITLE
Toggle edit button to formalization

### ISSUE THREAD

**Issue by terezanovot** [normativeai/frontend#22]
When using annotations to formalize legal text, it is not possible to add implicit logical formulas that does not come directly from the text but are only implied. 
Example: second sentence has a relation with the first one that does not directly come from the raw text. But it has to be included. I think this could be simply resolved by adding toggle edit button, so the user can add this implicit relation between sentences/articles (...) himself?

**Comment by shaolintl** [comment]
We have the advanced tab for adding formalization directly. Does that solve your problem?

**Comment by terezanovot** [comment]
Yes, actually, thanks! I didn't know there was a cooperation between formulas in formalization and advanced. However, now, I cannot delete entries in advanced.

**Comment by lex-lex** [comment]
There should be red delete buttons that do that. They become clickable when in edit-mode (when doing a mouse-over it should say something like "enable edit mode for deleting"). Or do I confuse things?

**Comment by shaolintl** [comment]
I confirm that when clicking on the red buttons, the norms in the advanced tabs stay. At least in the "Rome regulation - annot." legislation.

**Comment by lex-lex** [comment]
Right, should work now.
