### ISSUE TITLE
Choosing from existing vocabulary doesnt support arguments

### ISSUE THREAD

**Issue by shaolintl** [normativeai/frontend#24]
When adding terms, one can select from existing vocabulary. This displays symbols only and ignore arguments. There might be different applications of the same symbol to different arguments. It would be nice to be able to see the "full" term including the arguments and this full term should also be what is inserted into the formalization.

**Comment by lex-lex** [comment]
Right, as a first step, I just use `full` instead of `name`. Same for the vocabulary overview tab. Do we need further changes?

**Comment by shaolintl** [comment]
I think it is enough for the tutorial. Maybe later we can think how to improve that.
