### ISSUE TITLE
Impossible to register a new account

### ISSUE THREAD

**Issue by terezanovot** [normativeai/frontend#26]
I tried to make trial account, but the registering is not working.

**Comment by shaolintl** [comment]
@terezanovot Can you be more specific? What happens, which error message do you get? At which step are you getting problems?

I did not manage to replicate this problem.

**Comment by terezanovot** [comment]
I fill in an e-mail and a password and click on "Register" button and nothing happens, not even error message.
https://nai.uni.lu/#theregistration

**Comment by shaolintl** [comment]
I see that a "user already exists message" appears. @lex-lex Maybe the message is not propogated to the user? @terezanovot Can you try to log in with these users? (in case you remember the password).

**Comment by terezanovot** [comment]
Great, you are right! It works. However , an error message would be handy concerning this.
