### ISSUE TITLE
Setting name of a new/edited legislation does not work

### ISSUE THREAD

**Issue by shaolintl** [normativeai/frontend#3]
1. set a name of a new theory or update a name of an existing theory
2. save
3. Go back to dashboard
4. Theory has old (default) name

**Comment by lex-lex** [comment]
This should have been adressed by 1af450db616cc9965eb489b64bab86251c5b4110.
Did you try the most recent version? I just pulled it onto nai.uni.lu.

**Comment by shaolintl** [comment]
I just tried editing again and it didnt work...

**Comment by lex-lex** [comment]
I cannot reproduce this error; any update on this?

**Comment by lex-lex** [comment]
I guess this is solved, isn't it? Reopen if this still occurs.
