### ISSUE TITLE
Adding new vocabulary in queries

### ISSUE THREAD

**Issue by shaolintl** [normativeai/frontend#30]
Our assumption was that new vocabulary is not required but since we deal with variables and the vocabulary has currently fixed variables, we do need it.

For example:

All men are mortal, Socrates is a man translates int
man(X) => mortal(X)
man(socrates)

The query will contain mortal(socrates) and we currently cannot achieve such a goal with the legislation vocabulary.

**Comment by lex-lex** [comment]
@shaolintl 
Okay, when I just did a rough test: Seems simple enough.
Only that when I annotate with a term that is not contained in the `autoVocabulary` of the underlying theory, save, reload, the annotation does not appear in the autoAssumptions.
Also, is there a field `autoVocabulary` for queries just like for theories?`If not, this would be required to have them displayed at the front end.

Here is the content of said query:
```html
<p>
  <span class="connective-depth-1 annotator-connective" id="2f889ffb-9f47-4df4-b912-1362944e050b" data-connective="or" title="Or">
    a
    <span class="annotator-term" id="588b8d7c-02eb-40a3-8944-93e2974997e5" data-term="aaa" title="aaa">sdia sidja</span>
    dja sdjia js
    <span class="annotator-term" id="c912f84c-60c6-41de-86fd-a90c783792a3" data-term="aaa" title="aaa">doija dj</span>
    as
  </span>
  id
</p>
<p>
  aij
  <span class="annotator-goal" id="d2cfc40e-5e16-43df-b784-c274de39cfaa" title="Goal">
    d oi
    <span class="connective-depth-1 annotator-connective" id="723949b3-0997-44eb-a6ed-ece47ff9c13c" data-connective="and" title="And">
      <span class="annotator-term" id="8873cab2-8e8f-49a9-a153-d0c145f1a142" data-term="aaa" title="aaa">ad</span>
      sj
      <span class="annotator-term" id="2b0cb2b0-abe8-47c2-80ff-f6b769639fda" data-term="asdasd" title="asdasd">ai s</span>
    </span>
    dia
  </span>
  jds asd
  <span class="annotator-term" id="718d8b97-3ba9-47aa-af8f-ec95121e5def" data-term="xaz" title="xaz">as</span>
  d
</p>
```

The last term (xaz) is not contained in the theory. However, I don't know if that's the problem. Maybe there is just an unrelated parsing error.

**Comment by shaolintl** [comment]
@lex-lex I have no problem adding autoVocabulary to queries but are you sure it is necessary? Maybe we can remove the vocabulary tab in the query page? I cannot see how this tab will help writing queries since it will contain the whole vocabulary of the legislation in addition to the query. Queries are also normally much smaller. What do you think?

**Comment by lex-lex** [comment]
Well, if the query should have a vocabulary tab then I think it is necessary. If not, then it's not necessary. Last meeting we agreed on designing the query view the same as the theory view; so this is my last information. If this is not needed, I will simply delete it.
I'm in favor of keeping it because why not; it's simple to do and to display and it could clarify problems if wrong (faulty spelled or so) terms are used.

**Comment by shaolintl** [comment]
ok, I have added the vocabulary of the query in autoVocabulary.

**Comment by lex-lex** [comment]
Done.
