### ISSUE TITLE
Use of the same propositional symbol for linguistically different sentences

### ISSUE THREAD

**Issue by matteo-si** [normativeai/frontend#38]

**Comment by matteo-si** [comment]
we cannot use the same symbol to denote two linguistically different sentences having the same meaning (e.g., D1), but we should be able to do this, because very often in a legal text the same thought is expressed by many different sentences and symbols are used to represent the thoughts expressed by a sentence:
For instance:
A) the seller, in accordance with the contract or this Convention, hands the goods over to a carrier
B) the seller is bound to arrange for carriage of the goods

A and B should be both denoted by D1

**Comment by shaolintl** [comment]
I believe this is not true. You can use the same constant (make sure it is starting with a lower letter) to denote any number of sentence parts. Please confirm and close.
