### ISSUE TITLE
We should remove all legislations and queries that are not used

### ISSUE THREAD

**Issue by matteo-si** [normativeai/frontend#44]
The webpage of the legislations and the one of the queries look quite chaotic, it would be good to keep only those that we are using and perhaps to use some specific (and unique) label for those that represent "works in progress". For instance: Rome Regulation, Art. X-Y vs Rome Regulation, Art X-Y (under development)

**Comment by shaolintl** [comment]
This account should not be used, except for experimentation. I suggest copying the relevant parts using copy/paste to concrete accounts. If we need to work together on the same legislation, we can create another shared account.
