### ISSUE TITLE
Consistency and validity checks do not return correct response

### ISSUE THREAD

**Issue by shaolintl** [normativeai/frontend#5]
When calling both, the reply is 
Got response: [object Object]

instead of Theorem (with proof) or Non-theorem for validity and Consistent for consistency,

**Comment by lex-lex** [comment]
Does 4b9b890596af5754d9eabe9b49b6b5d1451b50a0 solve this? (Proof display is not yet implemented), pulled to nai already.

**Comment by lex-lex** [comment]
Consistency checks now have better responses: 4abb0fc0d0a8653a008610b05e56ab3cf02315ca
