### ISSUE TITLE
Change the input language for queries

### ISSUE THREAD

**Issue by matteo-si** [normativeai/frontend#6]

**Comment by shaolintl** [comment]
Hi @matteo-si, which change exactly do you have in mind?

**Comment by matteo-si** [comment]
In the sense that queries should be formulated in some natural-language-close normalized syntax.

**Comment by shaolintl** [comment]
I agree, but it will also make sense to have the same language for the legislations, no?

**Comment by matteo-si** [comment]
Yes, indeed it would be good to change everything at some point. However, for the time being, it would be useful to add a description of the Fact Base at least

**Comment by lex-lex** [comment]
(Increasingly nice) Reconstruction of formulas as natural-language-close syntax is definitely a goal and will be addressed in further work.  
As a first, naive, step, I will add description column in the Assumption table for queries (this is what you meant, right?).
@shaolintl Will the back end support this when I just add more fields to the JSON object?

**Comment by shaolintl** [comment]
Maybe it would be useful to have instead just the vocabulary of the legislation shown somehow on the query view? Once can easily reconstruct the assumptions meaning when facing the vocabulary,

@lex-lex The back end will probably just ignore them. I will need to add the properties specifically. Just tell me which ones in case you add them.

**Comment by lex-lex** [comment]
I guess this is obsolete now as queries and formalizations are constructed from natural language text. Reopen if you disagree.
