### ISSUE TITLE
Warning on exit without save

### ISSUE THREAD

**Issue by lex-lex** [normativeai/frontend#9]
When changing the contents of a query or legislation, and I close the windows (or navigate somewhere else in the app), the browser should give a warning saying "you have unsaved changes, do you really want to proceed?" or so. What do you think?

**Comment by shaolintl** [comment]
Yes, this would be useful.

**Comment by lex-lex** [comment]
On it.

**Comment by lex-lex** [comment]
I implemented  a simple version that works in Chrome and Firefox for me (Fedora Linux). But as web development goes, this of course does not mean that it works in general or is free of bugs. Can you test it a bit?

**Comment by shaolintl** [comment]
I just tried it on Chrome and Firefox (Debian Linux) and could not see any change. I tried both editing queries and theories and when clicking the buttons (consistency and run) it was executed on the original formula before the editing. Was it pushed to the server?

**Comment by lex-lex** [comment]
Ah, sorry, I forget to pull on the nai server. Just did it. Please check now.

**Comment by shaolintl** [comment]
Seems to work fine.
